---
title: Environmental Justice Reserach
author: 'Claire Madden'
date: '2020-01-09'
slug: ej
categories: []
tags:
  - spatial
  - data
subtitle: 'Understanding the Relationship Between Dry Domestic Wells and Disadvantaged Communities in the Central Valley, CA'
summary: 'Environmental Justice Implications of a Groundwater Dependent Domestic Water Supply'
authors: []
lastmod: '2020-01-09T15:02:21-08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, include = FALSE}

library(tidyverse)
library(RColorBrewer)
library(ggrepel)


data <- read_csv("ALLdrywells_ratios.csv") %>%
  mutate(percentdry = ratio*100)


data1 <- data %>% 
  filter(ratio < 1)

```


```{r, include = FALSE}

trial_boxplot <- ggplot(data1, aes(x = tenpercbins, y = percentdry))+
  geom_boxplot()+
  geom_jitter(width = 0.1, alpha = 0.4, aes(color = tenpercbins))+
  scale_color_brewer(palette = "Spectral", direction = -1)+
  theme_bw()+
  theme(legend.position = "none", axis.text.x = element_text(angle = 20, size = 8, hjust = 1))+
  labs(x = "CalEnviroScreen Score Percentile \n(0% is least disadvantaged, 100% is most disadvantaged)", 
       y = "Percent of total domestic wells reported dry \nby California census tract", 
       title = "Occurance of Dry Domestic Wells in California \nby Disadvantaged Community Score")
  


trial_boxplot
```






without zeros

```{r, echo = FALSE, warning=FALSE}



nozeros<-data %>% 
  filter(ratio > 0)


nozerobox <- ggplot(nozeros, aes(x = tenpercbins, y = ratio))+
  geom_boxplot()+
  geom_jitter(width = 0.4, alpha = 0.7, aes(color = tenpercbins))+
  scale_color_brewer(palette = "Spectral", direction = -1)+
  scale_y_continuous(expand = c(0,0), breaks = seq(0,1,by = 0.1), limits = c(0,1))+
  theme_classic()+
  theme(legend.position = "none", 
        axis.text.y = element_text(size = 10),
        axis.text.x = element_text(angle = 20, size = 10, hjust = 0.5, vjust = 0.8), 
        plot.title = element_text(hjust = 0.5))+
  labs(x = "CalEnviroScreen Score Percentile \n(0% is least disadvantaged, 100% is most disadvantaged)", 
       y = "Ratio of Dry Wells to Total Domestic Wells \nby California Census Tract", 
       title = "Occurance of Dry Domestic Wells in California \nby Disadvantaged Community Rank")
  
  


nozerobox
```



```{r, include = FALSE}

trial_scatter <- ggplot(data, aes(x = CESscoreP, y = percentdry))+
  geom_point()+
  theme_bw()


trial_scatter
```

```{r, include = FALSE}

#calculate percent of total dry wells in each 10percentile range

#cant figure out how to save as character with "%" sign at the end so will have to manually input each percentage to the labels below

zerototen <- length(which(nozeros$tenpercbins == "0%-10%"))*(100/232)
tentotwenty <- length(which(nozeros$tenpercbins == "10%-20%"))*(100/232)
twentytothirty <- length(which(nozeros$tenpercbins == "20%-30%"))*(100/232)
thirtytoforty <- length(which(nozeros$tenpercbins == "30%-40%"))*(100/232)
fortytofifty <- length(which(nozeros$tenpercbins == "40%-50%"))*(100/232)
fiftytosixty <- length(which(nozeros$tenpercbins == "50%-60%"))*(100/232)
sixtytoseventy <- length(which(nozeros$tenpercbins == "60%-70%"))*(100/232)
seventytoeighty <- length(which(nozeros$tenpercbins == "70%-80%"))*(100/232)
eightytoninety <- length(which(nozeros$tenpercbins == "80%-90%"))*(100/232)
ninetytoonehund <- length(which(nozeros$tenpercbins == "90%-100%"))*(100/232)
```



```{r, echo = FALSE, warning=FALSE}
```


```{r, echo = FALSE, warning=FALSE}
nozeroscatter <- ggplot(nozeros, aes(x = CESscoreP, y = percentdry))+
  geom_point(aes(color = tenpercbins), size = 3)+
  scale_color_brewer(palette = "Spectral", direction = -1)+
  scale_x_continuous(expand = c(0,0), breaks = seq(0,102, by = 10), limits = c(0,102))+
  scale_y_continuous(expand = c(0,0), breaks = seq(0,100, by = 10), limits = c(0,100))+
  theme_classic()+
  annotate("label", x = 5, y = 95, round(label = zerototen, digits =2), color = "#5E4FA2", size = 6)+
  annotate("label", x = 15, y = 95, label = tentotwenty, color = "#3288BD", size = 6)+
  annotate("label", x = 25, y = 95, label = twentytothirty, color = "#66C2A5", size = 6)+
  annotate("label", x = 35, y = 95, label = thirtytoforty, color = "#ABDDA4", size = 6)+
  annotate("label", x = 45, y = 95, label = fortytofifty, color = "olivedrab3", size = 6)+
  annotate("label", x = 55, y = 95, label = fiftytosixty, color = "gold", size = 6)+
  annotate("label", x = 65, y = 95, label = sixtytoseventy, color = "#FDAE61", size = 6)+
  annotate("label", x = 75, y = 95, label = seventytoeighty, color = "#F46D43", size = 6)+
  annotate("label", x = 85, y = 95, label = eightytoninety, color = "#D53E4F", size = 6)+
  annotate("label", x = 95, y = 95, label = ninetytoonehund, color = "#9E0142", size = 6)+
  geom_vline(xintercept=c(10,20,30,40,50,60,70,80,90,100), linetype="dotted", color = "grey30")+
  labs(x = "CalEnviroScreen Score Percentile",
       y = "Percent of Domestic Wells Reported Dry \nby Census Tract")+
  theme(legend.position = "none")



nozeroscatter
```


```{r, echo = FALSE, warning=FALSE}
```



try to map!


```{r, echo = FALSE, warning=FALSE}


library(sf)
library(ggplot2)
library(tmap)
library(tmaptools)
library(leaflet)
library(dplyr)

options(scipen = 9999)


pointdata <- data %>% 
  filter(ratio > 0) %>% 
  select("lat", "long") %>% 
  rename(latitude = lat, longitude = long)

mymap <- st_read("CESsimple.shp", stringsAsFactors = FALSE) 

mypoints<-st_read("ALL_drywells.shp", stringsAsFactors = FALSE)


map_and_data <- inner_join(mymap,data)

cv <- read_sf("SGMA_Dissolved_Central_Valley.shp")


map <- ggplot()+
  geom_sf(data = map_and_data, aes(fill = tenpercbins))+
  scale_fill_brewer(palette = "Spectral", direction = -1)+
  geom_sf(data = mypoints, size = 1, color = "black", shape = 21)+
  theme_classic()+
  labs(x = "Longitude",
       y = "Latitude",
       fill = "CalEnviroScreen \nPercentile")


map





```












```{r, echo = FALSE, warning=FALSE}


map1 <- ggplot()+
  geom_sf(data = map_and_data, aes(fill = tenpercbins), color = NA)+
  scale_fill_brewer(palette = "Spectral", direction = -1)+
  theme_classic()+
  labs(x = "Longitude",
       y = "Latitude",
       fill = "CalEnviroScreen Percentile",
       title = "Distribution of Dry Wells and Disadvantaged Communities in California")



map1

```




```{r}
###########revisit!!##########################


CESpolygons <- read_sf("ALL_drywells_CES_join.shp")

map2_and_data <- inner_join(CESpolygons,data)

ca <- read_sf("California.shp")


map2 <- ggplot()+
  geom_sf(data = map2_and_data, aes(fill = tenpercbins), color = NA)+
  scale_fill_brewer(palette = "Spectral", direction = -1)+
  geom_sf(data = ca, aes(fill = NA))+
  theme_classic()+
  theme(legend.position = "none")+
  labs(x = "Longitude",
       y = "Latitude",
       fill = "CalEnviroScreen Percentile")


map2





```

```{r}

simplehist <- ggplot(data = nozeros, aes(x = CESscoreP))+
  geom_histogram(bins = 10, breaks = seq(0, 100, 10))+
  scale_x_continuous(expand = c(0,0), breaks = seq(0,100,10))

simplehist


labs<- c("1%", "0.5%", "1.5%", "4%", "8%", "11%", "14%", "23.5%", "24.5%", "12%")


histscatter <- ggplot(nozeros, aes(x = CESscoreP))+
  geom_histogram(bins = 10, breaks = seq(0,100,10), aes(alpha = I(.3)))+
  geom_point(aes(y = percentdry, color = tenpercbins), size = 3)+
  scale_color_brewer(palette = "Spectral", direction = -1)+
  scale_x_continuous(expand = c(0,0), breaks = seq(0,100, by = 10), limits = c(0,100))+
  scale_y_continuous(expand = c(0,0), breaks = seq(0,100, by = 10), limits = c(0,100), sec.axis = sec_axis(~. *0.5, name = "Percent of Census Tracts With\nAt Least One Reported Dry Well (bars)"))+
  theme_classic()+
  geom_vline(xintercept=c(10,20,30,40,50,60,70,80,90,100), linetype="dotted", color = "grey30")+
  labs(x = "CalEnviroScreen Score Percentile",
       y = "Percent of Domestic Wells Reported Dry\n In Each Census Tract (points)")+
  theme(legend.position = "none")


histscatter


```




```{r}


refhist <- ggplot(data = data, aes(x = CESscoreP))+
  geom_histogram(bins = 10, breaks = seq(0,100,10), aes(alpha = I(0.3)))+
  geom_vline(xintercept=c(10,20,30,40,50,60,70,80,90,100), linetype="dotted", color = "grey30")+
  theme_classic()+
  scale_x_continuous(expand = c(0,0), breaks = seq(0,100, by = 10), limits = c(0,100))+
  scale_y_continuous(expand = c(0,0))


refhist

```


